### ISSUE TITLE
examples/numbers/Example.elm does not compile

### ISSUE THREAD

**Issue by martinos** [mgold/elm-socketio#1]
When I tried to compile examples/numbers/Example.elm. I have got this error:

Detected errors in 1 module.
## ERRORS in examples/numbers/Example.elm ######################################

-- TYPE MISMATCH ---------------------------------- examples/numbers/Example.elm

The 2nd argument to function `emit` has an unexpected type.

32|                                        SocketIO.emit eventName (i+1)
                                                                    ^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    String

    number

-- TYPE MISMATCH ---------------------------------- examples/numbers/Example.elm

The 2nd argument to function `emit` has an unexpected type.

16|                                 SocketIO.emit eventName 0
                                                            ^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    String

    number

**Comment by mgold** [comment]
Taken care of, thanks for reporting!
