### ISSUE TITLE
File path is too long on windows

### ISSUE THREAD

**Issue by bruno-cadorette** [mgold/elm-socketio#5]
When downloading the package on windows, I get the error message that the file path is too long. The problem is in example/node_modules/socket.io.

It would be nice if you could remove that example or just put it in another package (elm-socketio-example)

**Comment by mgold** [comment]
...Seriously, Microsoft?

I suppose I could include a package.json file so people would download the node modules themselves.

Do you have the exact text of the error?

**Comment by bruno-cadorette** [comment]
Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Downloading mgold/elm-socketio

Error: failed with 'mgold-elm-socketio-ddd55d2/examples/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/engine.io-parser/node_modules/arraybuffer.slice/package.json: openBinaryFile: does not exist (No such file or directory)' when sending request to
    <http://github.com/mgold/elm-socketio/zipball/2.0.2/>

**Comment by mgold** [comment]
How does that indicate that the filepath is too long?

**Comment by bruno-cadorette** [comment]
Oops sorry I got the wrong error, the funny things is that the error is different depending on the context, sometimes I get the earlier error, sometimes I get this one

To install mgold/elm-socketio I would like to add the following
dependency to elm-package.json:

    "mgold/elm-socketio": "2.0.2 <= v < 3.0.0"

May I add that to elm-package.json for you? (y/n) y

Some new packages are needed. Here is the upgrade plan.

  Install:
    mgold/elm-socketio 2.0.2

Do you approve of this plan? (y/n) y
Downloading mgold/elm-socketio

Error: failed with 'CreateDirectory "mgold-elm-socketio-ddd55d2\\examples\\node_modules\\socket.io\\node_modules\\engine.io\\node_modules\\engine.io-parser\\node_modules\\arraybuffer.slice": does not
exist (The filename or extension is too long.)' when sending request to
    <http://github.com/mgold/elm-socketio/zipball/2.0.2/>

**Comment by mgold** [comment]
Okay, I'll release a fix for this today or tomorrow.

**Comment by mgold** [comment]
Fix has been pushed to master. I'm going to let it sit for a few hours before releasing the package so I can see if there's anything else I want to include in the patch release.

**Comment by bruno-cadorette** [comment]
Thanks :)

**Comment by mgold** [comment]
2.0.3 is published. :tada:
